import {
  collection,
  doc,
  getDoc,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  query,
  where,
  orderBy,
  serverTimestamp,
} from "firebase/firestore";
import { db } from "@/lib/firebase";
import { PHOTOS_COLLECTION } from "./photo.config";
import type { Photo, PhotoCategory, PhotoCreateInput } from "./photo.types";

/**
 * Reference to the photos collection in Firestore.
 */
const photosCollection = collection(db, PHOTOS_COLLECTION);

/**
 * Creates a new photo document in Firestore.
 * Automatically injects creation and taken timestamps.
 * @param data The photo metadata to be saved.
 * @returns The unique document ID generated by Firestore.
 */
export async function createPhoto(data: PhotoCreateInput): Promise<string> {
  const docRef = await addDoc(photosCollection, {
    ...data,
    createdAt: serverTimestamp(),
    takenAt: serverTimestamp(),
  });

  return docRef.id;
}

/**
 * Updates an existing photo document in Firestore.
 * Crucial for the AdminPhotoEditPage functionality.
 * @param id The document ID of the photo to update.
 * @param data The partial data payload to merge into the document.
 */
export async function updatePhoto(id: string, data: Partial<Omit<Photo, "id" | "createdAt">>): Promise<void> {
  const ref = doc(db, PHOTOS_COLLECTION, id);
  await updateDoc(ref, data);
}

/**
 * Permanently deletes a photo document from Firestore.
 * @param id The document ID of the photo to delete.
 */
export async function deletePhoto(id: string): Promise<void> {
  const ref = doc(db, PHOTOS_COLLECTION, id);
  await deleteDoc(ref);
}

/**
 * Retrieves a single photo by its document ID.
 * @param id The requested document ID.
 * @returns The photo object, or null if the document does not exist.
 */
export async function getPhotoById(id: string): Promise<Photo | null> {
  const ref = doc(db, PHOTOS_COLLECTION, id);
  const snap = await getDoc(ref);

  if (!snap.exists()) {
    return null;
  }

  return { id: snap.id, ...(snap.data() as Omit<Photo, "id">) };
}

/**
 * Retrieves a list of published photos for a specific category.
 * Ordered chronologically by the takenAt timestamp.
 * * WARNING: This query requires a Firestore Composite Index on
 * fields: category (ASC), published (ASC), takenAt (DESC).
 * * @param category The specific photo category to filter by.
 * @returns An array of photo objects.
 */
export async function getPhotosByCategory(category: PhotoCategory): Promise<Photo[]> {
  const q = query(
    photosCollection,
    where("category", "==", category),
    where("published", "==", true),
    orderBy("takenAt", "desc"),
  );

  const snap = await getDocs(q);

  return snap.docs.map(doc => ({
    id: doc.id,
    ...(doc.data() as Omit<Photo, "id">),
  }));
}
